version: 3

tasks:

  run:core:
    dir: core
    cmd: go run ./cmd/core -- -e ../config/.core.local.env -c ../config/core.local.config.yaml -p ../prompts

  run:tg:
    dir: tg
    cmds:
      - source .venv/Scripts/activate
      - ENV_FILE="../config/.tg.local.env" CONFIG_FILE="../config/tg.local.config.yaml" python main.py

  run:ui:
    dir: ui
    cmd: CONFIG_PATH="../config" ENV_FILE=".ui.local.env" npm run dev

  buf:
    cmd: buf generate