// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chat.proto

//

package chatconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	chat "core/internal/pg/chat"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ChatServiceName is the fully-qualified name of the ChatService service.
	ChatServiceName = "chat.ChatService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ChatServiceAskProcedure is the fully-qualified name of the ChatService's Ask RPC.
	ChatServiceAskProcedure = "/chat.ChatService/Ask"
)

// ChatServiceClient is a client for the chat.ChatService service.
type ChatServiceClient interface {
	Ask(context.Context, *connect.Request[chat.AskRequest]) (*connect.Response[chat.AskResponse], error)
}

// NewChatServiceClient constructs a client for the chat.ChatService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewChatServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ChatServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	chatServiceMethods := chat.File_chat_proto.Services().ByName("ChatService").Methods()
	return &chatServiceClient{
		ask: connect.NewClient[chat.AskRequest, chat.AskResponse](
			httpClient,
			baseURL+ChatServiceAskProcedure,
			connect.WithSchema(chatServiceMethods.ByName("Ask")),
			connect.WithClientOptions(opts...),
		),
	}
}

// chatServiceClient implements ChatServiceClient.
type chatServiceClient struct {
	ask *connect.Client[chat.AskRequest, chat.AskResponse]
}

// Ask calls chat.ChatService.Ask.
func (c *chatServiceClient) Ask(ctx context.Context, req *connect.Request[chat.AskRequest]) (*connect.Response[chat.AskResponse], error) {
	return c.ask.CallUnary(ctx, req)
}

// ChatServiceHandler is an implementation of the chat.ChatService service.
type ChatServiceHandler interface {
	Ask(context.Context, *connect.Request[chat.AskRequest]) (*connect.Response[chat.AskResponse], error)
}

// NewChatServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewChatServiceHandler(svc ChatServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	chatServiceMethods := chat.File_chat_proto.Services().ByName("ChatService").Methods()
	chatServiceAskHandler := connect.NewUnaryHandler(
		ChatServiceAskProcedure,
		svc.Ask,
		connect.WithSchema(chatServiceMethods.ByName("Ask")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chat.ChatService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ChatServiceAskProcedure:
			chatServiceAskHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedChatServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedChatServiceHandler struct{}

func (UnimplementedChatServiceHandler) Ask(context.Context, *connect.Request[chat.AskRequest]) (*connect.Response[chat.AskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chat.ChatService.Ask is not implemented"))
}
