# Generated from chat.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.11.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync

from .chat_pb import AskRequest, AskResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class ChatService(Protocol):
    async def ask(self, request: AskRequest, ctx: RequestContext[AskRequest, AskResponse]) -> AskResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class ChatServiceASGIApplication(ConnectASGIApplication[ChatService]):
    def __init__(
        self,
        service: ChatService | AsyncGenerator[ChatService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/chat.ChatService/Ask": Endpoint.unary(
                    method=MethodInfo(
                        name="Ask",
                        service_name="chat.ChatService",
                        input=AskRequest,
                        output=AskResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.ask,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/chat.ChatService"


class ChatServiceClient(ConnectClient):
    async def ask(
        self,
        request: AskRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> AskResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Ask",
                service_name="chat.ChatService",
                input=AskRequest,
                output=AskResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class ChatServiceSync(Protocol):
    def ask(self, request: AskRequest, ctx: RequestContext[AskRequest, AskResponse]) -> AskResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class ChatServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: ChatServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/chat.ChatService/Ask": EndpointSync.unary(
                    method=MethodInfo(
                        name="Ask",
                        service_name="chat.ChatService",
                        input=AskRequest,
                        output=AskResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.ask,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/chat.ChatService"


class ChatServiceClientSync(ConnectClientSync):
    def ask(
        self,
        request: AskRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> AskResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Ask",
                service_name="chat.ChatService",
                input=AskRequest,
                output=AskResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
