# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: chat.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
import grpclib


@dataclass
class AskRequest(betterproto.Message):
    prompt: str = betterproto.string_field(1)


@dataclass
class AskResponse(betterproto.Message):
    completion: str = betterproto.string_field(1)


class ChatServiceStub(betterproto.ServiceStub):
    async def ask(self, *, prompt: str = "") -> AskResponse:
        request = AskRequest()
        request.prompt = prompt

        return await self._unary_unary(
            "/chat.ChatService/Ask",
            request,
            AskResponse,
        )
