# Generated from ping.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.11.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync

from .ping_pb import PingRequest, PingResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class PINGService(Protocol):
    async def ping(self, request: PingRequest, ctx: RequestContext[PingRequest, PingResponse]) -> PingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class PINGServiceASGIApplication(ConnectASGIApplication[PINGService]):
    def __init__(
        self,
        service: PINGService | AsyncGenerator[PINGService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/ping.PINGService/Ping": Endpoint.unary(
                    method=MethodInfo(
                        name="Ping",
                        service_name="ping.PINGService",
                        input=PingRequest,
                        output=PingResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.ping,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/ping.PINGService"


class PINGServiceClient(ConnectClient):
    async def ping(
        self,
        request: PingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> PingResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Ping",
                service_name="ping.PINGService",
                input=PingRequest,
                output=PingResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class PINGServiceSync(Protocol):
    def ping(self, request: PingRequest, ctx: RequestContext[PingRequest, PingResponse]) -> PingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class PINGServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: PINGServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/ping.PINGService/Ping": EndpointSync.unary(
                    method=MethodInfo(
                        name="Ping",
                        service_name="ping.PINGService",
                        input=PingRequest,
                        output=PingResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.ping,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/ping.PINGService"


class PINGServiceClientSync(ConnectClientSync):
    def ping(
        self,
        request: PingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> PingResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Ping",
                service_name="ping.PINGService",
                input=PingRequest,
                output=PingResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
