# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ping.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
import grpclib


@dataclass
class PingRequest(betterproto.Message):
    msg: str = betterproto.string_field(1)


@dataclass
class PingResponse(betterproto.Message):
    msg: str = betterproto.string_field(1)


class PINGServiceStub(betterproto.ServiceStub):
    async def ping(self, *, msg: str = "") -> PingResponse:
        request = PingRequest()
        request.msg = msg

        return await self._unary_unary(
            "/ping.PINGService/Ping",
            request,
            PingResponse,
        )
