// @generated by protoc-gen-es v2.14.1
// @generated from file chat.proto (package chat, syntax proto3)
/* eslint-disable */

//

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file chat.proto.
 */
export const file_chat = /*@__PURE__*/
  fileDesc("CgpjaGF0LnByb3RvEgRjaGF0IhwKCkFza1JlcXVlc3QSDgoGcHJvbXB0GAEgASgJIiEKC0Fza1Jlc3BvbnNlEhIKCmNvbXBsZXRpb24YASABKAkyOwoLQ2hhdFNlcnZpY2USLAoDQXNrEhAuY2hhdC5Bc2tSZXF1ZXN0GhEuY2hhdC5Bc2tSZXNwb25zZSIAQhdaFWNvcmUvaW50ZXJuYWwvcGcvY2hhdGIGcHJvdG8z");

/**
 * Describes the message chat.AskRequest.
 * Use `create(AskRequestSchema)` to create a new message.
 */
export const AskRequestSchema = /*@__PURE__*/
  messageDesc(file_chat, 0);

/**
 * Describes the message chat.AskResponse.
 * Use `create(AskResponseSchema)` to create a new message.
 */
export const AskResponseSchema = /*@__PURE__*/
  messageDesc(file_chat, 1);

/**
 * @generated from service chat.ChatService
 */
export const ChatService = /*@__PURE__*/
  serviceDesc(file_chat, 0);

