// @generated by protoc-gen-connect-es v1.7.0
// @generated from file chat.proto (package chat, syntax proto3)
/* eslint-disable */
// @ts-nocheck

//

import { AskRequest, AskResponse } from "./chat_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service chat.ChatService
 */
export const ChatService = {
  typeName: "chat.ChatService",
  methods: {
    /**
     * @generated from rpc chat.ChatService.Ask
     */
    ask: {
      name: "Ask",
      I: AskRequest,
      O: AskResponse,
      kind: MethodKind.Unary,
    },
  }
};

