// @generated by protoc-gen-connect-es v1.7.0
// @generated from file chat.proto (package chat, syntax proto3)
/* eslint-disable */
// @ts-nocheck

//

import { AskRequest, AskResponse } from "./chat_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service chat.ChatService
 */
export declare const ChatService: {
  readonly typeName: "chat.ChatService",
  readonly methods: {
    /**
     * @generated from rpc chat.ChatService.Ask
     */
    readonly ask: {
      readonly name: "Ask",
      readonly I: typeof AskRequest,
      readonly O: typeof AskResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

