// @generated by protoc-gen-es v2.14.1
// @generated from file chat.proto (package chat, syntax proto3)
/* eslint-disable */

//

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file chat.proto.
 */
export declare const file_chat: GenFile;

/**
 * @generated from message chat.AskRequest
 */
export declare type AskRequest = Message<"chat.AskRequest"> & {
  /**
   * @generated from field: string prompt = 1;
   */
  prompt: string;
};

/**
 * Describes the message chat.AskRequest.
 * Use `create(AskRequestSchema)` to create a new message.
 */
export declare const AskRequestSchema: GenMessage<AskRequest>;

/**
 * @generated from message chat.AskResponse
 */
export declare type AskResponse = Message<"chat.AskResponse"> & {
  /**
   * @generated from field: string completion = 1;
   */
  completion: string;
};

/**
 * Describes the message chat.AskResponse.
 * Use `create(AskResponseSchema)` to create a new message.
 */
export declare const AskResponseSchema: GenMessage<AskResponse>;

/**
 * @generated from service chat.ChatService
 */
export declare const ChatService: GenService<{
  /**
   * @generated from rpc chat.ChatService.Ask
   */
  ask: {
    methodKind: "unary";
    input: typeof AskRequestSchema;
    output: typeof AskResponseSchema;
  },
}>;

