// @generated by protoc-gen-connect-es v1.7.0
// @generated from file ping.proto (package ping, syntax proto3)
/* eslint-disable */
// @ts-nocheck

//

import { PingRequest, PingResponse } from "./ping_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ping.PINGService
 */
export const PINGService = {
  typeName: "ping.PINGService",
  methods: {
    /**
     * @generated from rpc ping.PINGService.Ping
     */
    ping: {
      name: "Ping",
      I: PingRequest,
      O: PingResponse,
      kind: MethodKind.Unary,
    },
  }
};

