// @generated by protoc-gen-connect-es v1.7.0
// @generated from file ping.proto (package ping, syntax proto3)
/* eslint-disable */
// @ts-nocheck

//

import { PingRequest, PingResponse } from "./ping_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ping.PINGService
 */
export declare const PINGService: {
  readonly typeName: "ping.PINGService",
  readonly methods: {
    /**
     * @generated from rpc ping.PINGService.Ping
     */
    readonly ping: {
      readonly name: "Ping",
      readonly I: typeof PingRequest,
      readonly O: typeof PingResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

