// @generated by protoc-gen-es v2.14.1
// @generated from file ping.proto (package ping, syntax proto3)
/* eslint-disable */

//

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ping.proto.
 */
export declare const file_ping: GenFile;

/**
 * @generated from message ping.PingRequest
 */
export declare type PingRequest = Message<"ping.PingRequest"> & {
  /**
   * @generated from field: string msg = 1;
   */
  msg: string;
};

/**
 * Describes the message ping.PingRequest.
 * Use `create(PingRequestSchema)` to create a new message.
 */
export declare const PingRequestSchema: GenMessage<PingRequest>;

/**
 * @generated from message ping.PingResponse
 */
export declare type PingResponse = Message<"ping.PingResponse"> & {
  /**
   * @generated from field: string msg = 1;
   */
  msg: string;
};

/**
 * Describes the message ping.PingResponse.
 * Use `create(PingResponseSchema)` to create a new message.
 */
export declare const PingResponseSchema: GenMessage<PingResponse>;

/**
 * @generated from service ping.PINGService
 */
export declare const PINGService: GenService<{
  /**
   * @generated from rpc ping.PINGService.Ping
   */
  ping: {
    methodKind: "unary";
    input: typeof PingRequestSchema;
    output: typeof PingResponseSchema;
  },
}>;

