// @generated by protoc-gen-es v2.14.1
// @generated from file ping.proto (package ping, syntax proto3)
/* eslint-disable */

//

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file ping.proto.
 */
export const file_ping = /*@__PURE__*/
  fileDesc("CgpwaW5nLnByb3RvEgRwaW5nIhoKC1BpbmdSZXF1ZXN0EgsKA21zZxgBIAEoCSIbCgxQaW5nUmVzcG9uc2USCwoDbXNnGAEgASgJMj4KC1BJTkdTZXJ2aWNlEi8KBFBpbmcSES5waW5nLlBpbmdSZXF1ZXN0GhIucGluZy5QaW5nUmVzcG9uc2UiAEIXWhVjb3JlL2ludGVybmFsL3BnL3BpbmdiBnByb3RvMw");

/**
 * Describes the message ping.PingRequest.
 * Use `create(PingRequestSchema)` to create a new message.
 */
export const PingRequestSchema = /*@__PURE__*/
  messageDesc(file_ping, 0);

/**
 * Describes the message ping.PingResponse.
 * Use `create(PingResponseSchema)` to create a new message.
 */
export const PingResponseSchema = /*@__PURE__*/
  messageDesc(file_ping, 1);

/**
 * @generated from service ping.PINGService
 */
export const PINGService = /*@__PURE__*/
  serviceDesc(file_ping, 0);

